export const TOGGLE_CHECK = 'TOGGLE_CHECK';
export const INC_NUMBER = 'INC_NUMBER';
export const DEC_NUMBER = 'DEC_NUMBER';
export const REMOVE_RECIPE = 'REMOVE_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const SET_EDITING_RECIPE = 'SET_EDITING_RECIPE';
export const SET_ADDING_NEW_RECIPE = 'SET_ADDING_NEW_RECIPE';
export const ADD_RECIPE = 'ADD_RECIPE';
asdf
